#!/usr/bin/env bash
{
while true;do
    location=$(find "/home/$USER/Pictures/Wallpapers" -type f -print0 | shuf -z -n 1)
    wal -q -n -i "$location"
    feh --bg-fill --no-fehbg "$(< "${HOME}/.cache/wal/wal")" 
  sleep 4m
done
} &


